### ISSUE TITLE
How to compute the similarity after training?

### ISSUE THREAD

**Issue by lucas-acc** [lateral/minkowski#2]
The computing method of similarity between vectors in hyperbolic space seems not same as that in Euclid space.

**Comment by benjaminwilson** [comment]
Hi, that's correct.  The vectors represent points on the hyperboloid model of hyperbolic space.  The distance between two points is calculated using their vectors according to formula (2) from this paper: 
  https://arxiv.org/pdf/1805.08207.pdf
You can simplify the calculation, too.  Since arccosh is monotone increasing, the rank order by similarity decreasing is the rank order according to the Minkowski dot product (again decreasing) (see the same paper for a definition of the Minkowski dot product - it is not the same as the dot product)

**Comment by lucas-acc** [comment]
Thank you, I need some time to figure it out.

**Comment by lucas-acc** [comment]
Hi, I implemented the similarity function. In the task of medicine domain entity taxonomy and entity relation extraction task, hyperbolic embedding looks better than Euclid embedding.

**Comment by benjaminwilson** [comment]
That sounds really interesting! Please do share your results, either here
or via email, if you get a chance.

**Comment by lucas-acc** [comment]
I sent the result to your email address in the paper, please check it.

**Comment by benjaminwilson** [comment]
Thanks very much!

I'll close this issue now.
